name: robomimic_venv
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_0
  - libmpdec=4.0.0=h4bc722e_0
  - libsqlite=3.49.1=hee588c1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_0
  - pip=25.0.1=pyh145f28c_0
  - python=3.13.3=hf636f53_100_cp313
  - python_abi=3.13=6_cp313
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_h4845f30_101
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - arm-pytorch-utilities==0.4.3
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - diffusers==0.33.1
      - docker-pycreds==0.4.0
      - egl-probe==1.0.2
      - etils==1.12.2
      - evdev==1.9.1
      - filelock==3.18.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.8.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - huggingface-hub==0.30.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - lxml==5.3.2
      - markdown==3.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mink==0.0.7
      - mpmath==1.3.0
      - mujoco==3.3.1
      - multidict==6.4.3
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.2.1
      - platformdirs==4.3.7
      - pluggy==1.5.0
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - py-spy==0.4.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pynput==1.8.1
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytorch-kinematics==0.7.5
      - pytorch-seed==0.2.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - qpsolvers==4.5.1
      - quadprog==0.1.13
      - regex==2024.11.6
      - requests==2.32.3
      - robomimic==0.4.0
      - robosuite==1.5.1
      - safetensors==0.5.3
      - scipy==1.15.2
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - setuptools==78.1.0
      - six==1.17.0
      - smmap==5.0.2
      - snakeviz==2.2.2
      - standard-imghdr==3.13.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==3.0.1
      - tokenizers==0.21.1
      - torch==2.6.0
      - torch-geometric==2.6.1
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.51.3
      - triton==3.2.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.19.9
      - werkzeug==3.1.3
      - yarl==1.19.0
      - zipp==3.21.0
