name: robomimic_venv
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.2=hee588c1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_1
  - pip=25.1.1=pyh8b19718_0
  - python=3.10.17=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.1.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - arm-pytorch-utilities==0.4.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - daqp==0.7.1
      - diffusers==0.33.1
      - docker-pycreds==0.4.0
      - egl-probe==1.0.2
      - etils==1.12.2
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - filelock==3.13.1
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.9.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - huggingface-hub==0.31.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - lxml==5.4.0
      - markdown==3.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mink==0.0.10
      - mpmath==1.3.0
      - mujoco==3.3.2
      - multidict==6.4.3
      - networkx==3.3
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - pluggy==1.5.0
      - propcache==0.3.1
      - protobuf==6.31.0
      - psutil==7.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pynput==1.8.1
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytorch-kinematics==0.7.5
      - pytorch-seed==0.2.0
      - pyyaml==6.0.2
      - qpsolvers==4.7.0
      - regex==2024.11.6
      - requests==2.32.3
      - robomimic==0.4.0
      - robosuite==1.5.1
      - safetensors==0.5.3
      - scipy==1.15.3
      - sentry-sdk==2.28.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==3.1.0
      - tokenizers==0.19.1
      - tomli==2.2.1
      - torch==2.7.0+cu128
      - torch-geometric==2.6.1
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tqdm==4.67.1
      - transformers==4.42.2
      - triton==3.3.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - wandb==0.19.11
      - werkzeug==3.1.3
      - yarl==1.20.0
      - zipp==3.21.0
prefix: /home/nicolas/miniconda3/envs/robomimic_venv
